controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%languages%'
    defaults:
        _locales: fr

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: POST

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale
