controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: fr|en|es
    defaults:
        _locales: fr

kernel:
    resource: ../src/Kernel.php
    type: annotation

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale
